
#stage 1
FROM python:3.14-slim AS builder

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt --target /app/libraries

#stage 2 
FROM gcr.io/distroless/python3-debian12 AS deployer

WORKDIR /app

COPY --from=builder /app/libraries /app/libraries

COPY . .

EXPOSE 80

ENV PYTHONPATH="/app/libraries"

CMD ["run.py"]
