name: Secrets Scan

on:
    workflow-call:
    
jobs:
    secrets-scan:
        runs-on: ubuntu-latest
        
        steps: 
            - name: checkout repository
              uses: actions/checkout@v4
              with:
                fetch-depth: 0 # fetch-depth 0 is required to scan the full git history

            - name: Run Gitleaks
              uses: gitleaks/gitleaks-action@v4
              env:
                GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}} # Automatically assigned by GitHub

    